### ISSUE TITLE
Flow constraint is redundant

### ISSUE THREAD

**Issue by kdambekalns** [bwaidelich/Wwwision.GraphQL#19]
This is redundant:

https://github.com/bwaidelich/Wwwision.GraphQL/blob/331b493078035760b95de8c6ddc4de62b07da71a/composer.json#L7

Since `^8.0` includes everything below `9.0`…

**Comment by bwaidelich** [comment]
Fixed with https://github.com/bwaidelich/Wwwision.GraphQL/releases/tag/5.0.2 thanks!
